### ISSUE TITLE
崩溃信息收集

### ISSUE THREAD

**Issue by phodal** [phodal/growth-ng#44]
以下结果来自 Google Analytcis

应用版本：299000
Android 版本：Android 7.1
设备：Moto X Style (clark_ds)
制造商：Motorola 
RAM (MB) ：3072 
屏幕尺寸：1440 × 2560 
屏幕密度 (dpi)： 560 
原生平台： armeabi-v7a 
OpenGL ES 版本： 3.1 
CPU 品牌： Qualcomm CPU 
型号： MSM8992

```
backtrace:
  native: pc 0000000000100e8e  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN16EsxProgramResult22AllocateUniformSymbolsEv+141)
  native: pc 0000000000103257  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN16EsxProgramResult6CreateEP26EsxProgramResultCreateDataj+86)
  native: pc 000000000010c6ef  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN17EsxShaderCompiler20AcquireProgramResultEPvi+46)
  native: pc 00000000000f9881  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN10EsxProgram10LinkStatusEP10EsxContext+32)
  native: pc 00000000000fbea1  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN10EsxProgram17LoadProgramBinaryEP10EsxContextjPKvi+128)
  native: pc 00000000000afd1b  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN10EsxContext15GlProgramBinaryEjjPKvi+90)
  native: pc 00000000000e1855  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN21EsxGlApiParamValidate15GlProgramBinaryEP11EsxDispatchjjPKvi+468)
  native: pc 000000000009bb43  /system/vendor/lib/egl/libGLESv2_adreno.so (glProgramBinary+34)
  native: pc 00000000014a80e7  /system/app/webview/webview.apk
```

**Comment by phodal** [comment]
应用版本：299000
Android 版本：Android 6.0
设备：Le Pro3 (le_zl1)
制造商：Leeco 
RAM (MB)： 4096 
屏幕尺寸： 1080 × 1920 
屏幕密度 (dpi) ： 480 
原生平台： armeabi-v7a 
OpenGL ES 版本： 3.1 
CPU 品牌： Qualcomm 
CPU 型号： MSM8996

```
backtrace:
  native: pc 0000000000018d34  /system/lib/libc.so (strlen+71)
  native: pc 00000000006b54ed  /system/vendor/lib/libllvm-glnext.so
  native: pc 00000000006b5633  /system/vendor/lib/libllvm-glnext.so
  native: pc 00000000006b9233  /system/vendor/lib/libllvm-glnext.so
  native: pc 000000000065a7f7  /system/vendor/lib/libllvm-glnext.so
  native: pc 00000000006c5dcf  /system/vendor/lib/libllvm-glnext.so (_Z21QGLCLoadProgramBinaryPvS_jP23QGLC_LINKPROGRAM_RESULT+34)
  native: pc 00000000001190eb  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN17EsxShaderCompiler21LoadProgramBinaryBlobEP10EsxContextP10EsxProgramPKvjP10EsxInfoLog+106)
  native: pc 00000000001065df  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN10EsxProgram17LoadProgramBinaryEP10EsxContextjPKvi+94)
  native: pc 00000000000bb93b  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN10EsxContext15GlProgramBinaryEjjPKvi+90)
  native: pc 00000000000a8043  /system/vendor/lib/egl/libGLESv2_adreno.so (glProgramBinary+34)
  native: pc 000000000038d0fb  /system/app/webview/webview.apk
  native: pc 00000000003948fd  /system/app/webview/webview.apk
  native: pc 000000000037513b  /system/app/webview/webview.apk
  native: pc 00000000003752a1  /system/app/webview/webview.apk
  native: pc 000000000037ebb7  /system/app/webview/webview.apk
  native: pc 000000000034eb95  /system/app/webview/webview.apk
  native: pc 00000000003842b1  /system/app/webview/webview.apk
  native: pc 000000000023402b  /system/app/webview/webview.apk
  native: pc 0000000000b595f7  /system/app/webview/webview.apk
  native: pc 0000000000b5b24d  /system/app/webview/webview.apk
  native: pc 0000000000b57ea3  /system/app/webview/webview.apk
  native: pc 0000000000303a61  /system/app/webview/webview.apk
  native: pc 0000000000313b67  /system/app/webview/webview.apk
  native: pc 000000000031401d  /system/app/webview/webview.apk
  native: pc 00000000003143ad  /system/app/webview/webview.apk
  native: pc 0000000000314e21  /system/app/webview/webview.apk
  native: pc 000000000031e5e9  /system/app/webview/webview.apk
  native: pc 0000000000313561  /system/app/webview/webview.apk
  native: pc 000000000032f251  /system/app/webview/webview.apk
  native: pc 000000000032c847  /system/app/webview/webview.apk
  native: pc 000000000003fa3b  /system/lib/libc.so (_ZL15__pthread_startPv+30)
  native: pc 0000000000019fe5  /system/lib/libc.so (__start_thread+6)
```
